INSPECT_INTEGER_METHODS_PY310 = (
    "╭──────────────── <class 'int'> ─────────────────╮\n"
    "│ int([x]) -> integer                            │\n"
    "│ int(x, base=10) -> integer                     │\n"
    "│                                                │\n"
    "│      denominator = 1                           │\n"
    "│             imag = 0                           │\n"
    "│        numerator = 1                           │\n"
    "│             real = 1                           │\n"
    "│ as_integer_ratio = def as_integer_ratio():     │\n"
    "│                    Return integer ratio.       │\n"
    "│        bit_count = def bit_count(): Number of  │\n"
    "│                    ones in the binary          │\n"
    "│                    representation of the       │\n"
    "│                    absolute value of self.     │\n"
    "│       bit_length = def bit_length(): Number of │\n"
    "│                    bits necessary to represent │\n"
    "│                    self in binary.             │\n"
    "│        conjugate = def conjugate(...) Returns  │\n"
    "│                    self, the complex conjugate │\n"
    "│                    of any int.                 │\n"
    "│       from_bytes = def from_bytes(bytes,       │\n"
    "│                    byteorder, *,               │\n"
    "│                    signed=False): Return the   │\n"
    "│                    integer represented by the  │\n"
    "│                    given array of bytes.       │\n"
    "│         to_bytes = def to_bytes(length,        │\n"
    "│                    byteorder, *,               │\n"
    "│                    signed=False): Return an    │\n"
    "│                    array of bytes representing │\n"
    "│                    an integer.                 │\n"
    "╰────────────────────────────────────────────────╯\n"
)

INSPECT_INTEGER_METHODS_PY311 = (
    "╭──────────────── <class 'int'> ─────────────────╮\n"
    "│ int([x]) -> integer                            │\n"
    "│ int(x, base=10) -> integer                     │\n"
    "│                                                │\n"
    "│      denominator = 1                           │\n"
    "│             imag = 0                           │\n"
    "│        numerator = 1                           │\n"
    "│             real = 1                           │\n"
    "│ as_integer_ratio = def as_integer_ratio():     │\n"
    "│                    Return integer ratio.       │\n"
    "│        bit_count = def bit_count(): Number of  │\n"
    "│                    ones in the binary          │\n"
    "│                    representation of the       │\n"
    "│                    absolute value of self.     │\n"
    "│       bit_length = def bit_length(): Number of │\n"
    "│                    bits necessary to represent │\n"
    "│                    self in binary.             │\n"
    "│        conjugate = def conjugate(...) Returns  │\n"
    "│                    self, the complex conjugate │\n"
    "│                    of any int.                 │\n"
    "│       from_bytes = def from_bytes(bytes,       │\n"
    "│                    byteorder='big', *,         │\n"
    "│                    signed=False): Return the   │\n"
    "│                    integer represented by the  │\n"
    "│                    given array of bytes.       │\n"
    "│         to_bytes = def to_bytes(length=1,      │\n"
    "│                    byteorder='big', *,         │\n"
    "│                    signed=False): Return an    │\n"
    "│                    array of bytes representing │\n"
    "│                    an integer.                 │\n"
    "╰────────────────────────────────────────────────╯\n"
)
